// start StorList colums ===============================================================================
export const TotalProductEntries = [
  { name: "ID", uid: "id", sortable: true },
  { name: "Product Name", uid: "productName", sortable: true },
  { name: "Upload Date", uid: "uploadDate" },
  { name: "Category", uid: "category" },
  { name: "Price", uid: "price" },
  { name: "Stock", uid: "stock" },
  { name: "Quantity", uid: "quantity" },
  { name: "Offers", uid: "offers" },
  { name: "Delivery Type", uid: "deliveryType" },
  { name: "Total Buyed", uid: "totalBuyed" },
  { name: "Product Revenue", uid: "productRevenue" },
  { name: "Saved Count", uid: "savedCount" },
  { name: "Image", uid: "image" },
  { name: "Rating", uid: "rating" },
  { name: "Status", uid: "status" },
  { name: "Pending Order", uid: "pendingOrder" },
  { name: "Success Order", uid: "successOrder" },
];
export const Defualt_Columns_TotalProductEntries = [
  "id",
  "productName",
  "category",
  "price",
  "status",
  "offers",
];

export const CategoriesList = [
  { name: "ID", uid: "id", sortable: true },
  { name: "Category Name", uid: "categoryName", sortable: true },
  { name: "Sub Category", uid: "subCategory" },
  { name: "Created Date", uid: "createdDate" },
  { name: "Subcategory Updated Data", uid: "subcategoryUpdatedData" },
  { name: "Store Name", uid: "storeName" },
  { name: "Update By", uid: "updateBy" },
  { name: "Quantity", uid: "quantity" },
  { name: "Offers", uid: "offers" },
  { name: "Delivery Type", uid: "deliveryType" },
  { name: "Total Buyed", uid: "totalBuyed" },
  { name: "Product Revenue", uid: "productRevenue" },
  { name: "Saved Count", uid: "savedCount" },
  { name: "Image", uid: "image" },
  { name: "Rating", uid: "rating" },
  { name: "Status", uid: "status" },
  { name: "Pending Order", uid: "pendingOrder" },
  { name: "Success Order", uid: "successOrder" },
  { name: "Vendor Name", uid: "vendorName" },
  { name: "Vendor Quantity", uid: "vendorQuantity" },
  { name: "Vendor Payment", uid: "vendorPayment" },
  { name: "Vendor Rating", uid: "vendorRating" },
  { name: "Vendor Pending Payment", uid: "vendorPendingPayment" },
  { name: "Location", uid: "location" },
  { name: "Status History", uid: "statusHistory" },
  { name: "Product Name", uid: "productName" },
];
export const Defualt_Columns_Categories_List = [
  "successOrder",
  "productName",
  "location",
  "storeName",
  "vendorName",
  "savedCount",
  "vendorQuantity",
];
export const CustomerRequest = [
  { name: "ID", uid: "id", sortable: true },
  { name: "Product Name", uid: "productName", sortable: true },
  { name: "Contact Information", uid: "contactInformation" },
  { name: "Created Date", uid: "createdDate" },
  { name: "Quantity", uid: "quantity" },
  { name: "Store Name", uid: "storeName" },
  { name: "Price", uid: "price" },
  { name: "Update By", uid: "updateBy" },
  { name: "Attachments", uid: "attachments" },
  { name: "Delivery Type", uid: "deliveryType" },
  { name: "Total Buyed", uid: "totalBuyed" },
  { name: "Product Revenue", uid: "productRevenue" },
  { name: "Resolution Notes", uid: "resolutionNotes" },
  { name: "Priority", uid: "priority" },
  { name: "Rating", uid: "rating" },
  { name: "Description", uid: "description" },
  { name: "Response Status", uid: "responseStatus" },
  { name: "Customer Name", uid: "customerName" },
  { name: "Billing Information", uid: "billingInformation" },
  { name: "Resolution Time", uid: "resolutionTime" },
  { name: "Customer Satisfaction", uid: "customerSatisfaction" },
  { name: "Feedback", uid: "feedback" },
];
export const Defualt_Columns_Customer_Request = [
  "customerName",
  "productName",
  "createdDate",
  "storeName",
  "deliveryType",
  "description",
  "priority",
];
export const RequestToAdmin = [
  { name: "ID", uid: "id", sortable: true },
  { name: "Product Name", uid: "productName", sortable: true },
  { name: "Contact Information", uid: "contactInformation" },
  { name: "Created Date", uid: "createdDate" },
  { name: "Quantity", uid: "quantity" },
  { name: "Store Name", uid: "storeName" },
  { name: "Price", uid: "price" },
  { name: "Update By", uid: "updateBy" },
  { name: "Attachments", uid: "attachments" },
  { name: "Delivery Type", uid: "deliveryType" },
  { name: "Total Buyed", uid: "totalBuyed" },
  { name: "Product Revenue", uid: "productRevenue" },
  { name: "Resolution Notes", uid: "resolutionNotes" },
  { name: "Priority", uid: "priority" },
  { name: "Rating", uid: "rating" },
  { name: "Description", uid: "description" },
  { name: "Response Status", uid: "responseStatus" },
  { name: "Customer Name", uid: "customerName" },
  { name: "Billing Information", uid: "billingInformation" },
  { name: "Resolution Time", uid: "resolutionTime" },
  { name: "Customer Satisfaction", uid: "customerSatisfaction" },
  { name: "Feedback", uid: "feedback" },
];
export const Defualt_Columns_Request_to_admin = [
  "productName",
  "productName",
  "price",
  "storeName",
  "customerName",
  "quantity",
  "rating",
];
export const NicknameVendorList = [
  { name: "Vendor ID", uid: "vendorID", sortable: true },
  { name: "Vendor Name", uid: "vendorName", sortable: true },
  { name: "Contact Person", uid: "contactPerson" },
  { name: "Update Date", uid: "updateDate" },
  { name: "Contact Email", uid: "contactEmail" },
  { name: "Contact Phone", uid: "contactPhone" },
  { name: "Vendor Address ", uid: "vendorAddress" },
  { name: "Billing Address", uid: "billingAddress" },
  { name: "Payment Method", uid: "paymentMethod" },
  { name: "Delivery Type", uid: "deliveryType" },
  { name: "Delivery Terms", uid: "deliveryTerms" },
  { name: "Emergency Contact", uid: "emergencyContact" },
  { name: "Saved Count", uid: "savedCount" },
  { name: "Image", uid: "image" },
  { name: "Rating", uid: "rating" },
  { name: "Status", uid: "status" },
];
export const Defualt_Columns_Nickname_Vendor_List = [
  "vendorName",
  "contactPerson",
  "categoryName",
  "updateDate",
  "emergencyContact",
  "vendorRating",
  "contactEmail",
];
// end StorList =================================================

// Vendor Login list ======================================================================================================

export const VendorRequestList = [
  { name: "Vendor ID", uid: "vendorID", sortable: true },
  { name: "Vendor Name", uid: "vendorName", sortable: true },
  { name: "Contact Person", uid: "contactPerson" },
  { name: "Update Date", uid: "updateDate" },
  { name: "Contact Email", uid: "contactEmail" },
  { name: "Contact Phone", uid: "contactPhone" },
  { name: "Vendor Address ", uid: "vendorAddress" },
  { name: "Billing Address", uid: "billingAddress" },
  { name: "Payment Method", uid: "paymentMethod" },
  { name: "Delivery Type", uid: "deliveryType" },
  { name: "Delivery Terms", uid: "deliveryTerms" },
  { name: "Emergency Contact", uid: "emergencyContact" },
  { name: "Saved Count", uid: "savedCount" },
  { name: "Image", uid: "image" },
  { name: "Rating", uid: "rating" },
  { name: "Status", uid: "status" },
];
export const Defualt_Columns_Vendor_Request_List = [
  "vendorName",
  "contactPerson",
  "categoryName",
  "updateDate",
  "emergencyContact",
  "vendorRating",
  "contactEmail",
];

export const VendorRequestToAdmin = [
  { name: "Request ID", uid: "requestID", sortable: true },
  { name: "Product Name", uid: "productName", sortable: true },
  { name: "Contact Person", uid: "contactPerson", sortable: true },
  { name: "Subject", uid: "subject" },
  { name: " Address", uid: "address" },
  { name: " Priority", uid: "priority" },
  { name: " Comments", uid: "comments" },
  { name: " Feedback", uid: "feedback" },
  { name: " Attachments", uid: "attachments" },
  { name: "Contact Email", uid: "contactEmail" },
  { name: "Contact Phone", uid: "contactPhone" },
  { name: "Follow-up Actions", uid: "followupActions" },
];
export const Defualt_Columns_Vendor_Request_to_admin = [
  "requestID",
  "productName",
  "contactPerson",
  "priority",
  "contactEmail",
  "contactPhone",
  "comments",
];
export const VendorStoreRequest = [
  { name: "Request ID", uid: "requestID", sortable: true },
  { name: "Requester Name", uid: "requesterName", sortable: true },
  { name: "Contact Person", uid: "contactPerson", sortable: true },
  { name: "Vendor Name", uid: "vendorName" },
  { name: " Contact Email", uid: "contactEmail" },
  { name: " Contact Phone", uid: "contactPhone" },
  { name: " Vendor Information", uid: "vendorInformation" },
  { name: " Billing Address", uid: "billingAddress" },
  { name: " Payment Method", uid: "paymentMethod" },
  { name: "Delivery Type", uid: "deliveryType" },
  { name: "Request Date", uid: "requestDate" },
  { name: "Emergency Contact", uid: "emergencyContact" },
  { name: "Delivery Date", uid: "deliveryDate" },
  { name: "Request Type", uid: "requestType" },
  { name: "Priority", uid: "priority" },
  { name: "Status", uid: "status" },
  { name: "Quantity", uid: "quantity" },
  { name: "Unit Price", uid: "unitPrice" },
  { name: "Total Cost", uid: "totalCost" },
  { name: "Service Description", uid: "serviceDescription" },
  { name: "Related Documents", uid: "relatedDocuments" },
  { name: "Legal Compliance", uid: "legalCompliance" },
  { name: "Urgency Level", uid: "urgencyLevel" },
  { name: "Shipping Information", uid: "shippingInformation" },
];
export const Defualt_Columns_Store_Request = [
  "vendorName",
  "requesterName",
  "contactPerson",
  "unitPrice",
  "contactEmail",
  "contactPhone",
  "totalCost",
];

export const VendorStoreList = [
  { name: "Store ID", uid: "storeID", sortable: true },
  { name: "Store Name", uid: "storeName", sortable: true },
  { name: "Address", uid: "address" },
  { name: "Contact Information", uid: "contactInformation" },

  { name: " Contact Email", uid: "contactEmail" },
  { name: " Contact Phone", uid: "contactPhone" },
  { name: " Store Manager", uid: "storeManager" },
  { name: "Opening Hours", uid: "openingHours" },
  { name: "Sales Performance", uid: "salesPerformance" },
  { name: "Product Description", uid: "productDescription" },
  { name: "Customer Ratings", uid: "customerRatings" },
  { name: "Availability", uid: "availability" },
  { name: "Status", uid: "status" },
  { name: " City", uid: "city" },
  { name: " State", uid: "state" },
  { name: " Zip Code", uid: "zipCode" },
];
export const Defualt_Columns_Vendor_Store_List = [
  "storeName",
  "productName",
  "contactInformation",
  "openingHours",
  "contactEmail",
  "contactPhone",
  "salesPerformance",
];


// Vendor Login list ====================================================